### ISSUE TITLE
Exception while updating prices

### ISSUE THREAD

**Issue by paveldomsa** [pcmind/degiro-java-client#5]
I can login, get portfolio, products, descriptions, etc with no issues.
Yesterday i've added realtime vwd price pooling and result is this expection
Any ideas?

[main] WARN DEGIRO - Field "totalDepositWithdrawal" not found in DPortfolioSummary: 0
[main] WARN DEGIRO - Field "todayDepositWithdrawal" not found in DPortfolioSummary: 0
[main] WARN DEGIRO - Session expired, clearing session tokens
[main] ERROR DEGIRO - Exception while updating prices
cat.indiketa.degiro.exceptions.DUnauthorizedException
	at cat.indiketa.degiro.DeGiroImpl.getResponseData(DeGiroImpl.java:501)
	at cat.indiketa.degiro.DeGiroImpl.requestAndValidate(DeGiroImpl.java:238)
	at cat.indiketa.degiro.DeGiroImpl.httpPost(DeGiroImpl.java:228)
	at cat.indiketa.degiro.DeGiroImpl.access$800(DeGiroImpl.java:71)
	at cat.indiketa.degiro.DeGiroImpl$DPricePoller.newVwdSession(DeGiroImpl.java:707)
	at cat.indiketa.degiro.DeGiroImpl$DPricePoller.poll(DeGiroImpl.java:643)

**Comment by pcmind** [comment]
This is a duplicate issue of #4.
